# dbt/dbt_project.yml

name: 'woolie_data_platform'
version: '2.0.0'
config-version: 2
require-dbt-version: '>=1.11.0'
flags:
  use_managed_iceberg: true
  use_materialization_v2: true        
  use_concurrent_microbatch: true

# This must match the name we used in profiles.yml
profile: 'woolie_data_platform'

# Directory configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean up the target folder on every run
clean-targets:
  - "target"
  - "dbt_packages"

# --- MODEL CONFIGURATIONS ---
# This is where we define the "Medallion" behavior
models:
  woolie_data_platform:
    # 1. Silver Layer: Incremental processing for efficiency
    silver:
      +schema: silver
      +materialized: incremental
      +incremental_strategy: merge
      +file_format: delta
    
    # 2. Gold Layer: Final tables for Power BI
    gold:
      +schema: gold
      +materialized: incremental
      +file_format: delta

  # --- PACKAGE CONFIGURATIONS ---
  # This moves the audit views out of 'gold' and into 'audit'
  dbt_project_evaluator:
    +schema: audit
    marts:
      dag:
        fct_marts_or_intermediate_dependent_on_source:
          +enabled: false

  
seeds:
  dbt_project_evaluator:
    +schema: audit


dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

vars:
  dbt_project_evaluator:
    # Tell the evaluator which folders correspond to which prefixes
    staging_directories: ['silver']
    intermediate_directories: ['silver']
    marts_directories: ['gold']
    documentation_coverage_target: 10
    test_coverage_target: 10
