name: woolie-platform-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - ipykernel
  - google-cloud-sdk  # Smart: Keeps Home WSL and VM in sync
  - pip:
      - python-dotenv
      - pandas
      - pyarrow
      - sqlmodel
      - google-cloud-storage
      - google-cloud-bigquery
      - google-cloud-pubsub
      - dbt-bigquery
      - dbt-core
      - fastapi[standard]
      - httpx
      - tenacity
      - dbt-databricks
      - databricks-sdk
      - pytest
      - pytest-mock
      - pytest-asyncio
      - click