melbourne_api:
  pipeline_name: "melbourne_city_data"
  dataset_name: null
  base_url: "https://data.melbourne.vic.gov.au/api/explore/v2.1/"
  resources:
    - name: "dwellings"
      write_disposition: "append"
      path: "catalog/datasets/residential-dwellings/records"
      params:
        order_by: "block_id"
        where: "block_id > 1"
        limit: 10
        offset: 0
    - name: "family_profile"
      write_disposition: "append"
      path: "catalog/datasets/families-with-children-profile-2016-aged-0-12-years/records"
      params:
        order_by: "value"
        where: "value > 0"
        limit: 10
        offset: 0