melbourne_api:
  pipeline_name: "melbourne_city_data"
  dataset_name: "bronze_zone"
  resources:
    - name: "dwellings"
      path: "catalog/datasets/residential-dwellings/records"
      params:
        order_by: "block_id"
        where: "block_id > 1"
        limit: 20
        offset: 0
    - name: "family_profile"
      path: "catalog/datasets/families-with-children-profile-2016-aged-0-12-years/records"
      params:
        order_by: "value"
        where: "value > 0"
        limit: 20
        offset: 0