resources:
  schemas:
    bronze_schema:
      name: bronze
      catalog_name: ${bundle.target}
      comment: "Raw ingestion layer for ${bundle.target}"

    silver_schema:
      name: silver
      catalog_name: ${bundle.target}
      comment: "Cleaned and modeled layer for ${bundle.target}"

    gold_schema:
      name: gold
      catalog_name: ${bundle.target}
      comment: "Business-ready reporting layer for ${bundle.target}"
    
    sandbox_schema:
      name: sandbox
      catalog_name: ${bundle.target}
      comment: "Test Data and play around and exploration for basic data exploration"

  volumes:
      checkpoint_volume:
        name: checkpoints
        catalog_name: ${bundle.target}
        schema_name: ${resources.schemas.bronze_schema.name}
        volume_type: MANAGED
        comment: "Storage for streaming checkpoints"